ls:
  .js: camelCase
  .ts: camelCase
  .jsx: PascalCase
  .tsx: PascalCase
  .d.ts: kebab-case

  src/pages:
    .tsx: lowercase

  src/:
    .dir: lowercase

ignore:
  - .git
  - node_modules
  - .next
  - .lintstagedrc.js
  - next.config.js
